title: <p align="center"> Rajeev Ranjan </p>
logo: /assets/img/DataAnalysis.jpg
description: A Comprehensive Guide for Data Analysis
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
